# Generated by Django 4.0 on 2021-12-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0006_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='none', verbose_name='توضیحات'),
        ),
    ]
