# Generated by Django 4.0 on 2022-06-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0014_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='teacher',
            field=models.CharField(default='مشخص نشده!!!', max_length=50),
        ),
    ]
