# Generated by Django 4.0 on 2022-01-28 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile_photo',
            options={'verbose_name': 'پروفایل', 'verbose_name_plural': 'پزوفایل ها'},
        ),
    ]
