# Generated by Django 4.0 on 2022-07-22 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_user_profile', '0002_alter_profile_photo_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile_photo',
        ),
    ]
