# Generated by Django 4.0 on 2022-07-22 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('eshop_user_profile', '0003_delete_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_photo',
            fields=[
                ('photo', models.ImageField(default='Def_prof/def.png', upload_to='users_profiles/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': 'پزوفایل ها',
            },
        ),
    ]
