# Generated by Django 4.0 on 2022-07-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_user_profile', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_photo',
            name='photo',
            field=models.ImageField(default='Def_prof/def.jpg', upload_to='users_profiles/'),
        ),
    ]
