# Generated by Django 4.0 on 2022-06-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reset_code',
            name='last_time_requestet',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='reset_code',
            name='reset_code',
            field=models.IntegerField(max_length=6, null=True),
        ),
    ]
