# Generated by Django 4.0 on 2022-06-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_account', '0002_reset_code_last_time_requestet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reset_code',
            name='reset_code',
            field=models.IntegerField(null=True),
        ),
    ]
