# Generated by Django 4.0 on 2022-06-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_account', '0005_alter_reset_password_reset_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='reset_password',
            name='reset_try_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reset_password',
            name='reset_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
