# Generated by Django 4.0 on 2022-06-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_account', '0006_reset_password_reset_try_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reset_password',
            name='is_unvalidated',
            field=models.BooleanField(default=False),
        ),
    ]
