# Generated by Django 4.0 on 2022-07-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_account', '0007_reset_password_is_unvalidated'),
    ]

    operations = [
        migrations.AddField(
            model_name='reset_password',
            name='Baned',
            field=models.BooleanField(default=False),
        ),
    ]
