# Generated by Django 4.0 on 2022-07-09 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_account', '0008_reset_password_baned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reset_password',
            old_name='Baned',
            new_name='is_baned',
        ),
    ]
