# Generated by Django 4.0 on 2022-07-22 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_account', '0010_profile_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile_photo',
        ),
    ]
