# Generated by Django 4.0 on 2022-01-14 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_tag', '0003_alter_tag_slug_ex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ex',
            name='tag',
        ),
    ]
