# Generated by Django 4.0 on 2022-01-14 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_tag', '0005_ex_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ex',
        ),
    ]
