# Generated by Django 4.0 on 2022-01-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0011_product_gallery'),
        ('eshop_tag', '0006_delete_ex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='products',
            field=models.ManyToManyField(to='eshop_products.Product', verbose_name='محصولات مربوطه'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='عنوان در یو ار ال'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=150, verbose_name='عنوان'),
        ),
    ]
