# Generated by Django 4.0 on 2022-01-22 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_tag', '0007_alter_tag_products_alter_tag_slug_alter_tag_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'برچسب ها', 'verbose_name_plural': 'برچسب'},
        ),
    ]
