# Generated by Django 4.0 on 2022-01-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='Logo',
            field=models.ImageField(blank=True, null=True, upload_to='Logo'),
        ),
    ]
