# Generated by Django 4.0 on 2022-01-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_settings', '0002_settings_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='about',
            field=models.TextField(blank=True),
        ),
    ]
