# Generated by Django 4.0 on 2022-01-24 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_contactUs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact_us_model',
            options={'verbose_name': 'تیکت ها', 'verbose_name_plural': 'تیکت'},
        ),
    ]
