# Generated by Django 4.0 on 2022-05-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_favlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite_list_details',
            options={'verbose_name': 'محصول درون لیست', 'verbose_name_plural': 'محصولات درون لیست'},
        ),
        migrations.AddField(
            model_name='favorite_list',
            name='is_have',
            field=models.BooleanField(default=False),
        ),
    ]
