# Generated by Django 4.0 on 2022-05-18 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_favlist', '0002_alter_favorite_list_details_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite_list',
            name='is_have',
        ),
    ]
