# Generated by Django 4.0 on 2022-05-18 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_favlist', '0003_remove_favorite_list_is_have'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite_list_details',
            name='List',
        ),
        migrations.RemoveField(
            model_name='favorite_list_details',
            name='product',
        ),
        migrations.DeleteModel(
            name='Favorite_list',
        ),
        migrations.DeleteModel(
            name='Favorite_list_details',
        ),
    ]
