# Generated by Django 4.0 on 2022-05-18 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0014_alter_product_slug'),
        ('eshop_favlist', '0005_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorite_list_details',
            new_name='details',
        ),
    ]
