# Generated by Django 4.0 on 2022-01-22 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products_category', '0002_alter_category_active_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی ها', 'verbose_name_plural': 'دسته بندی'},
        ),
    ]
