# Generated by Django 4.0 on 2022-01-22 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_sliders', '0002_alter_slider_description_alter_slider_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'اسلایدر ها', 'verbose_name_plural': 'اسلایدر'},
        ),
    ]
