# Generated by Django 4.0 on 2022-01-30 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0013_product_views'),
        ('eshop_sliders', '0003_alter_slider_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eshop_products.product'),
        ),
    ]
