# Generated by Django 4.0 on 2022-01-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='add_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
